def URLify(string, realLength):
	mString = list(string)												# O(n)
	i, j = realLength - 1, len(string) - 1								# O(1)
	while i <= j and j > 0:												# O(n)
		if mString[i] != ' ': 												# O(1)
			mString[i], mString[j] = mString[j], mString[i]						# O(1)
			i, j = i - 1, j - 1													# O(1)
		elif mString[i] == ' ' and mString[j] == ' ':						# O(1)
			mString[j - 2], mString[j - 1], mString[j] = '%', '2', '0'			# O(1)
			j -= 3																# O(1)
			while mString[i] == ' ': i -= 1										# O(n)
	return ''.join(mString)

print(URLify('Mr John Smith    ', 13))
print(URLify('Mr John Smith      ', 14))
print(URLify('MrJohnSmith', 11))
print(URLify(' Mr John    ', 8))
print(URLify('   ', 1))
print(URLify('', 0))